---
- name: Setup catalogue microserivce
  hosts: localhost
  become: yes
  tasks:
    # - name: Disable nodejs package using dnf module
    #   ansible.builtin.dnf:
    #     name: nodejs
    #     state: absent
    # - name: Add nodejs package using dnf module
    #   ansible.builtin.dnf:
    #     name: "nodejs-18.*"
    #     state: present

    - name: Disable nodejs package using command module
      ansible.builtin.command: dnf module disable nodejs -y   
    - name: Add nodejs 18 package using command module
      ansible.builtin.command: dnf module enable nodejs:18 -y
      
    - name: install nodejs 18
      ansible.builtin.package:
        name: nodejs
        state: present