---

- name: payment microservice
  hosts: payments
  become: yes
  tasks:
    - name: intall packages
      ansible.builtin.package:
        name: '{{item}}'
        state: present
      loop:
        - python36
        - gcc
        - python3-devel
    
    - name: add roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download payment application source code zip file
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/payment.zip
        dest: /tmp
    
    - name: Extract cart.zip to /app directory
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
    
    - name: install dependencies
      ansible.builtin.command: pip3.6 install -r requirements.txt
      args:
        chdir: /app

    - name: copy payment svc file
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system

    - name: realod daemon
      ansible.builtin.systemd_service:
        daemon_reload: true  

    - name: start and enable payment
      ansible.builtin.service:
        name: payment
        state: started
        enabled: yes