---

- name: setting rabbitmq for roboshop
  hosts: localhost
  become: yes
  tasks:
    - name: configur yum repos
      ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash ; 
      curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: install rabbitmq server
      ansible.builtin.package:
        name: rabbitmq-server
        state: present

    - name: enable and starte rabbtitmq
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes
    
    - name: creating user for roboshop and setting permsissions to user
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"